substitutions:
  name: "svitlobot"
  project_name: "svitlobot.vitich"
  project_version: "1.0.0"
  comment: "esphome client (esp8266)"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$name
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp01_1m
  restore_from_flash: true

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3
  ota: false

wifi:
  ap: {}

captive_portal:

http_request:
  useragent: "${name} (${project_version})"
  verify_ssl: false
  timeout: 2s

globals:
  # URL1
  - id: url1_send_quality
    type: int
    restore_value: no
    initial_value: '-1'

  - id: url1_session
    type: bool
    restore_value: no
    initial_value: 'false'

  # URL2
  - id: url2_send_quality
    type: int
    restore_value: no
    initial_value: '-1'

  - id: url2_session
    type: bool
    restore_value: no
    initial_value: 'false'

  # SvitloBot
  - id: svitlobot_send_quality
    type: int
    restore_value: no
    initial_value: '-1'

  - id: svitlobot_session
    type: bool
    restore_value: no
    initial_value: 'false'

script:
  # URL1
  - id: url1_send_state
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(url1_key).has_state();'
          then:
            - globals.set:
                id: url1_session
                value: 'true'
            - http_request.get:
                url: !lambda |-
                  return id(url1_key).state.c_str();
                on_response:
                  then:
                    - lambda: id(url1_set_state)->execute(response->status_code, "");
                    - globals.set:
                        id: url1_session
                        value: 'false'
            - if:
                condition:
                  lambda: 'return id(url1_session);'
                then:
                  - script.execute:
                      id: url1_set_state
                      code: -1
                      response: ""
            - component.update: url1_quality
    mode: queued

  - id: url1_set_state
    parameters:
      code: int
      response: string
    then:
      - lambda: |-
          if (code == 200)
          {
            ESP_LOGD("URL1", "Send status - success");
            id(url1_send_status).publish_state(true);
            id(url1_send_quality) = id(url1_send_quality) < 0 ? 100 : std::min(100, ++id(url1_send_quality));
          }
          else
          {
            if (code > 0)
            {
              ESP_LOGE("URL1", "Send status - not success with response code: %d", code);
            }
            id(url1_send_status).publish_state(false);
            id(url1_send_quality) = id(url1_send_quality) < 0 ? 0 : std::max(0, --id(url1_send_quality));
          }
    mode: queued

  # URL2
  - id: url2_send_state
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(url2_key).has_state();'
          then:
            - globals.set:
                id: url2_session
                value: 'true'
            - http_request.get:
                url: !lambda |-
                  return id(url2_key).state.c_str();
                on_response:
                  then:
                    - lambda: id(url2_set_state)->execute(response->status_code, "");
                    - globals.set:
                        id: url2_session
                        value: 'false'
            - if:
                condition:
                  lambda: 'return id(url2_session);'
                then:
                  - script.execute:
                      id: url2_set_state
                      code: -1
                      response: ""
            - component.update: url2_quality
    mode: queued

  - id: url2_set_state
    parameters:
      code: int
      response: string
    then:
      - lambda: |-
          if (code == 200)
          {
            ESP_LOGD("URL2", "Send status - success");
            id(url2_send_status).publish_state(true);
            id(url2_send_quality) = id(url2_send_quality) < 0 ? 100 : std::min(100, ++id(url2_send_quality));
          }
          else
          {
            if (code > 0)
            {
              ESP_LOGE("URL2", "Send status - not success with response code: %d", code);
            }
            id(url2_send_status).publish_state(false);
            id(url2_send_quality) = id(url2_send_quality) < 0 ? 0 : std::max(0, --id(url2_send_quality));
          }
    mode: queued

  # SvitloBot
  - id: svitlobot_send_state
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(svitlobot_key).has_state();'
          then:
            - globals.set:
                id: svitlobot_session
                value: 'true'
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "http://api.svitlobot.in.ua/channelPing?channel_key=" + id(svitlobot_key).state).c_str();
                on_response:
                  then:
                    - lambda: id(svitlobot_set_state)->execute(response->status_code, "");
                    - globals.set:
                        id: svitlobot_session
                        value: 'false'
            - if:
                condition:
                  lambda: 'return id(svitlobot_session);'
                then:
                  - script.execute:
                      id: svitlobot_set_state
                      code: -1
                      response: ""
            - component.update: svitlobot_quality
    mode: queued

  - id: svitlobot_set_state
    parameters:
      code: int
      response: string
    then:
      - lambda: |-
          if (code == 200)
          {
            ESP_LOGD("SvitloBot", "Send status - success");
            id(svitlobot_send_status).publish_state(true);
            id(svitlobot_send_quality) = id(svitlobot_send_quality) < 0 ? 100 : std::min(100, ++id(svitlobot_send_quality));
          }
          else
          {
            if (code > 0)
            {
              ESP_LOGE("SvitloBot", "Send status - not success with response code: %d", code);
            }
            id(svitlobot_send_status).publish_state(false);
            id(svitlobot_send_quality) = id(svitlobot_send_quality) < 0 ? 0 : std::max(0, --id(svitlobot_send_quality));
          }
    mode: queued

interval:
  - interval: 1min
    then:
      - script.execute: url1_send_state
      - script.execute: url2_send_state
      - script.execute: svitlobot_send_state

text:
  - platform: template
    name: "URL1 (http not https)"
    id: url1_key
    optimistic: true
    min_length: 0
    max_length: 120
    mode: text
    restore_value: true
    icon: mdi:link-variant
    entity_category: config
    disabled_by_default: true

  - platform: template
    name: "URL2 (http not https)"
    id: url2_key
    optimistic: true
    min_length: 0
    max_length: 120
    mode: text
    restore_value: true
    icon: mdi:link-variant
    entity_category: config
    disabled_by_default: true

  - platform: template
    name: "SvitloBot Key"
    id: svitlobot_key
    optimistic: true
    min_length: 0
    max_length: 15
    mode: text
    restore_value: true
    icon: mdi:key-chain-variant
    entity_category: config
    disabled_by_default: true

binary_sensor:
  - platform: template
    name: "URL1 Status"
    id: url1_send_status
    icon: mdi:lan-connect
  - platform: template
    name: "URL2 Status"
    id: url2_send_status
    icon: mdi:lan-connect
  - platform: template
    name: "SvitloBot Status"
    id: svitlobot_send_status
    icon: mdi:lan-connect

sensor:
  - platform: template
    name: "URL1 Delivery Quality"
    id: url1_quality
    lambda: |-
      if (!id(url1_key).has_state() || id(url1_send_quality) < 0)
      {
        return NAN;
      }
      return id(url1_send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement

  - platform: template
    name: "URL2 Delivery Quality"
    id: url2_quality
    lambda: |-
      if (!id(url2_key).has_state() || id(url2_send_quality) < 0)
      {
        return NAN;
      }
      return id(url2_send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement

  - platform: template
    name: "SvitloBot Delivery Quality"
    id: svitlobot_quality
    lambda: |-
      if (!id(svitlobot_key).has_state() || id(svitlobot_send_quality) < 0)
      {
        return NAN;
      }
      return id(svitlobot_send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement

  - platform: uptime
    name: "SvitloBot Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "SvitloBot WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

button:
  - platform: restart
    name: "SvitloBot Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "SvitloBot Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: SvitloBot ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "SvitloBot IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "SvitloBot Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "SvitloBot Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network
