substitutions:
  name: "svitlobot"
  project_name: "svitlobot.vitich"
  project_version: "1.0.0"
  comment: "esphome client (esp8266)"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$name
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp01_1m
  restore_from_flash: true

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3
  ota: false

wifi:
  ap: {}

captive_portal:

http_request:
  useragent: "${name} (${project_version})"
  verify_ssl: false
  timeout: 2s

globals:
  - id: svitlobot_send_quality
    type: int
    restore_value: no
    initial_value: '-1'
  - id: svitlobot_session
    type: int
    restore_value: no
    initial_value: '0'

  - id: url1_send_quality
    type: int
    restore_value: no
    initial_value: '-1'
  - id: url1_session
    type: int
    restore_value: no
    initial_value: '0'

  - id: url2_send_quality
    type: int
    restore_value: no
    initial_value: '-1'
  - id: url2_session
    type: int
    restore_value: no
    initial_value: '0'

script:
  - id: send_to_svitlobot
    parameters:
      retries: int
    then:
      - if:
          condition:
            lambda: 'return id(svitlobot_session) == 0 && wifi.connected && id(svitlobot_key).has_state();'
          then:
            - globals.set:
                id: svitlobot_session
                value: '1'
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "http://api.svitlobot.in.ua/channelPing?channel_key=" + id(svitlobot_key).state).c_str();
                on_response:
                  then:
                    - lambda: |-
                        int code = response->status_code;
                        if (code == 200) {
                          id(svitlobot_send_quality) = id(svitlobot_send_quality) < 0 ? 100 : std::min(100, ++id(svitlobot_send_quality));
                        } else {
                          id(svitlobot_send_quality) = id(svitlobot_send_quality) < 0 ? 0 : std::max(0, --id(svitlobot_send_quality));
                          if (retries < 3) id(send_to_svitlobot).execute(retries + 1);
                        }
                        id(svitlobot_session) = 0;

  - id: send_to_url1
    parameters:
      retries: int
    then:
      - if:
          condition:
            lambda: 'return id(url1_session) == 0 && wifi.connected && id(url1_key).has_state();'
          then:
            - globals.set:
                id: url1_session
                value: '1'
            - http_request.get:
                url: !lambda 'return id(url1_key).state.c_str();'
                on_response:
                  then:
                    - lambda: |-
                        int code = response->status_code;
                        if (code == 200) {
                          id(url1_send_quality) = id(url1_send_quality) < 0 ? 100 : std::min(100, ++id(url1_send_quality));
                        } else {
                          id(url1_send_quality) = id(url1_send_quality) < 0 ? 0 : std::max(0, --id(url1_send_quality));
                          if (retries < 3) id(send_to_url1).execute(retries + 1);
                        }
                        id(url1_session) = 0;

  - id: send_to_url2
    parameters:
      retries: int
    then:
      - if:
          condition:
            lambda: 'return id(url2_session) == 0 && wifi.connected && id(url2_key).has_state();'
          then:
            - globals.set:
                id: url2_session
                value: '1'
            - http_request.get:
                url: !lambda 'return id(url2_key).state.c_str();'
                on_response:
                  then:
                    - lambda: |-
                        int code = response->status_code;
                        if (code == 200) {
                          id(url2_send_quality) = id(url2_send_quality) < 0 ? 100 : std::min(100, ++id(url2_send_quality));
                        } else {
                          id(url2_send_quality) = id(url2_send_quality) < 0 ? 0 : std::max(0, --id(url2_send_quality));
                          if (retries < 3) id(send_to_url2).execute(retries + 1);
                        }
                        id(url2_session) = 0;

interval:
  - interval: 1min
    then:
      - script.execute:
          id: send_to_svitlobot
          retries: 0
      - script.execute:
          id: send_to_url1
          retries: 0
      - script.execute:
          id: send_to_url2
          retries: 0

text:
  - platform: template
    name: "SvitloBot Key"
    id: svitlobot_key
    mode: text
    optimistic: true
    min_length: 0
    max_length: 15
    restore_value: true
    icon: mdi:key-chain-variant

  - platform: template
    name: "URL1 (http)"
    id: url1_key
    mode: text
    optimistic: true
    min_length: 0
    max_length: 120
    restore_value: true
    icon: mdi:link-variant

  - platform: template
    name: "URL2 (http)"
    id: url2_key
    mode: text
    optimistic: true
    min_length: 0
    max_length: 120
    restore_value: true
    icon: mdi:link-variant

binary_sensor:
  - platform: template
    name: "SvitloBot Status"
    id: svitlobot_send_status
    icon: mdi:lan-connect
  - platform: template
    name: "URL1 Status"
    id: url1_send_status
    icon: mdi:lan-connect
  - platform: template
    name: "URL2 Status"
    id: url2_send_status
    icon: mdi:lan-connect

sensor:
  - platform: template
    name: "SvitloBot Delivery Quality"
    id: svitlobot_quality
    lambda: 'return id(svitlobot_send_quality) < 0 ? NAN : id(svitlobot_send_quality);'
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement

  - platform: template
    name: "URL1 Delivery Quality"
    id: url1_quality
    lambda: 'return id(url1_send_quality) < 0 ? NAN : id(url1_send_quality);'
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement

  - platform: template
    name: "URL2 Delivery Quality"
    id: url2_quality
    lambda: 'return id(url2_send_quality) < 0 ? NAN : id(url2_send_quality);'
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement

  - platform: uptime
    name: "SvitloBot Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "SvitloBot WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

button:
  - platform: restart
    name: "SvitloBot Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "SvitloBot Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: SvitloBot ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "SvitloBot IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "SvitloBot Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "SvitloBot Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network
